### ISSUE TITLE
Filtered history list resets to "all" after closing a history detail page

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#722]
Scenario:
1. From the dashboard, I tapped day 3 collection
2. I was taken to the history page, pre-filtered by "day 3"
3. I tapped the first artifact record then closed it.
4. I was taken back to history page but the filter resets to "all"

**Comment by wrenr** [comment]
This is currently implemented because the response summary is a new page. Viewing a single response is rendered as a new page, and the content on this page overwrites the current page.
When the new response modal UI element is implemented, this will not happen because the modal will appear over the current page, and disappear to reveal the current page when the modal is dismissed.

**Comment by ctrance** [comment]
fixed
