### ISSUE TITLE
Replace the red X icon with back button

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#757]
I emailed you the back button from Lauren, please use that as a replacement for red X button on history details page.

**Comment by ctrance** [comment]
app shows gray x on a charcoal box instead of Lauren's back button

**Comment by wrenr** [comment]
Sent to the team earlier today:
This UI element being a back button no longer makes sense now that the history detail has been changed to a modal that opens and closes with a sliding animation (and not a link that simply navigates the page backwards). A close button with some kind of X is necessary if they still require a change to the icon, and the style of this icon must match other similar icons in the app since this modal will now be used elsewhere such as in the Upload Queue. In fact, since it's in the top right corner by necessity, it should especially match the style of the Hamburger menu and the icons that are in the header top right corner.

Since their original concern was that the button looked too much like a delete button, now that the red has been removed and replaced with a background color that matches the app header, and the button has been moved to the expected place that a close button properly is (top corner) on a pop-up modal, this concern has been taken care of.

Examples of other icons and their appearance:
https://github.com/ucla/ohmageX/blob/develop/www/img/icon/add.svg
 
https://github.com/ucla/ohmageX/blob/develop/www/img/icon/sync.svg
https://github.com/ucla/ohmageX/blob/develop/www/img/icon/menu-open.svg


Full list of app icons here:
https://github.com/ucla/ohmageX/tree/develop/www/img/icon

**Comment by ctrance** [comment]
Upload Queue details is now a modal, closing this.
