### ISSUE TITLE
Mobilize- Upload Queue looks off on iphone 6

### ISSUE THREAD

**Issue by ctrance** [ucla/ohmageX#772]
Upload Queue list looks off on iphone6 and the upload all icon on the header no longer appears. Steve said the CSS might have messed up. Please fix.
![img_7565](https://cloud.githubusercontent.com/assets/1034174/9822948/3bbab4de-5878-11e5-8c83-b453a801d0d2.PNG)

**Comment by wrenr** [comment]
This is happening because the letters "Upload Queue" combined with the "(1)" are too wide to fit in the horizontal space. Thinking of a solution.

**Comment by stevenolen** [comment]
I think the (1) shouldn't actually be in the title of the page, just in the menu bar. I feel like it's a little weird in the title of the page?

**Comment by wrenr** [comment]
added appearance change

**Comment by ctrance** [comment]
Will retest once I get the new build for Mobilize

**Comment by stevenolen** [comment]
@ctrance new builds are available: commit is `9c389b7025469202360b9a77f7a09215717b0df5`

**Comment by ctrance** [comment]
@stevenolen - Now I can see it, thanks!

**Comment by ctrance** [comment]
I think I like the counter in a parenthesis better than the new look. Also the counter still shows in the title. I agree with @stevenolen to only show the counter on the menu.
![img_7577 1](https://cloud.githubusercontent.com/assets/1034174/9862365/3f1c1cfe-5aed-11e5-8768-c3e41f7832c4.PNG) 
![img_7578 1](https://cloud.githubusercontent.com/assets/1034174/9862374/4be61016-5aed-11e5-8c72-07aa6ce31f83.PNG)

**Comment by stevenolen** [comment]
Not to be picky and push this issue futher...but if we're going to do something like that, instead of a superscript (which feels a bit odd) could we instead use a [badge](http://getbootstrap.com/components/#badges)?  this is the exact use case of that design pattern..

**Comment by ctrance** [comment]
@stevenolen - a badge would be perfect!

**Comment by hongsudt** [comment]
@wrenr @stevenolen @ctrance  I agree that the superscript looks wierd. It just reminds me of a footnote or reference section. 

What about for now just take the number of responses in the upload queue from the upload page title? But leave that under the hamburger menu though.

**Comment by wrenr** [comment]
During my evaluation process when adding or updating UI elements, a badge (as linked) was considered. The UX challenge here is that the additional content must be smaller to provide for excessive horizontal width of the parent content in a fixed region with potentially very narrow space on devices. The title bar must have room for four elements: two icon buttons, a title text of variable length, and now a marker of variable length (the marker is what the source code calls the text that was formerly in parentheses).

For the marker, parentheses plus content are too wide, especially if it ever gets to two digits (a situation which has already been encountered with a recent beta user that added multiple responses to their upload queue). The additional text can't be shrunk and kept on the same baseline, because this violates typographic flow and opens up platform rendering issues, a greater issue because the text appears in vertically centered contexts. A superscript avoids these problems. A badge could be visually pleasing, but any badge with readable spacing is going to have the same horizontal width issue as parentheses, unless the text is shrunk to an unreadable size.

The purpose of keeping the marker the same in both places is to provide UI consistency, so the horizontal menu correlates directly with the marker in the title, a relationship that the user can always trust. This is essential since the target users are not experienced technologists, as proven with the request to add the "Missing Surveys? Download more" button on the Surveys section. I am open to discussion of any discrete UI affordances that create a direct benefit to the user when there are separate and not equivalent indicators for a navigation element and its page, and are worth risking this trust. It's worth considering that there was also a request to prepare a Mobilize build quickly. Thoughts so we can move forward?

**Comment by hongsudt** [comment]
What about trying one or all of the following options?

* making the hamburger menu a little bit smaller..
* only capitalize the first letter instead of all letters on the title
* On upload queue, remove the # of items in the queue from the title, and
have a summary line that summarize # items e.g. There are xx items to be
uploaded.

**Comment by wrenr** [comment]
restoring parentheses and changed header icon spacing, fix pushed

**Comment by hongsudt** [comment]
great.. Thanks!!

@ctrace can you check on ios?

**Comment by ctrance** [comment]
I can now see "upload all" icon and the items in the queue appears good now! Closing this!
![img_7622 1](https://cloud.githubusercontent.com/assets/1034174/9907071/406c1e78-5c42-11e5-9d80-114e2136e91c.PNG)
